language: java
install: true

jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10

cache:
  directories:
    - $HOME/.m2

script:
- mvn install -B

after_success:
  - "[[ $TRAVIS_BRANCH == \"development\" ]] && [[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && [[ ${TRAVIS_TAG} == '' ]] && mvn deploy -B -DskipTests -s settings.xml"
  - bash <(curl -s https://codecov.io/bash)


