language: java
install: true
script:
- mvn install -B
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10

after_success:
  - "[[ $TRAVIS_BRANCH == \"development\" ]] && [[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && [[ ${TRAVIS_TAG} == '' ]] && mvn deploy -B -DskipTests -s settings.xml"
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.m2
